import { WorldType, World, Mission } from './types';

export const WORLDS: World[] = [
  {
    id: WorldType.VEHICLE,
    name: "Vehicle Valley",
    color: "bg-blue-500",
    iconName: "Car",
    voiceIntro: "Welcome to Vehicle Valley! Start your engines!",
    audioKey: "world_vehicle_intro",
    unlockCount: 0
  },
  {
    id: WorldType.DINO,
    name: "Dino Jungle",
    color: "bg-green-700",
    iconName: "Trees",
    voiceIntro: "Welcome to the Dino Jungle! Watch out for giant lizards!",
    audioKey: "world_dino_intro",
    unlockCount: 0
  },
  {
    id: WorldType.CASTLE,
    name: "Castle Kingdom",
    color: "bg-indigo-600",
    iconName: "Castle",
    voiceIntro: "Enter the Castle Kingdom! Prepare for an epic battle!",
    audioKey: "world_castle_intro",
    unlockCount: 0
  },
  {
    id: WorldType.LAVA,
    name: "Lava Land",
    color: "bg-orange-700",
    iconName: "Flame",
    voiceIntro: "Warning! The floor is lava! Welcome to Lava Land!",
    audioKey: "world_lava_intro",
    unlockCount: 0
  },
  {
    id: WorldType.SPACE,
    name: "Space Base",
    color: "bg-violet-900",
    iconName: "Rocket",
    voiceIntro: "3... 2... 1... Blast off! Welcome to the Space Base!",
    audioKey: "world_space_intro",
    unlockCount: 0
  }
];

export const LEVEL_1_MISSIONS: Mission[] = [
  // --- VEHICLE MISSIONS (Level 1) ---
  {
    id: 'vehicle-racer',
    title: 'Speed Racer',
    voicePrompt: 'Build a racing car! Make it low and flat. Add a giant spoiler for speed!',
    audioScript: 'Build a racing car! Make it low, and flat. Add a giant spoiler, for speed!',
    audioKey: 'mission_vehicle_racer',
    iconName: 'Trophy',
    color: 'bg-red-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-monster',
    title: 'Monster Truck',
    voicePrompt: 'Build a Monster Truck! Use your biggest wheels. Make it huge!',
    audioScript: 'Build a Monster Truck! Use your biggest wheels. Make it... huge!',
    audioKey: 'mission_vehicle_monster',
    iconName: 'Truck',
    color: 'bg-green-600',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-police',
    title: 'Police Pursuit',
    voicePrompt: 'Police car time! Build it with red and blue lights on top.',
    audioScript: 'Police car time! Build it with red, and blue lights on top.',
    audioKey: 'mission_vehicle_police',
    iconName: 'Siren',
    color: 'bg-blue-600',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-fire',
    title: 'Fire Rescue',
    voicePrompt: 'Fire truck! Make it long. Add a ladder that spins around.',
    audioScript: 'Fire truck! Make it long. Add a ladder... that spins around!',
    audioKey: 'mission_vehicle_fire',
    iconName: 'Flame',
    color: 'bg-orange-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-dozer',
    title: 'Bulldozer',
    voicePrompt: 'Build a bulldozer! Make it strong and yellow. Add a scoop!',
    audioScript: 'Build a bulldozer! Make it strong, and yellow. Don\'t forget to add a scoop!',
    audioKey: 'mission_vehicle_dozer',
    iconName: 'Hammer',
    color: 'bg-yellow-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-fly',
    title: 'Future Car',
    voicePrompt: 'Future car! It needs wings, not wheels. Ready to fly?',
    audioScript: 'Future car! It needs wings, not wheels. Ready to fly?',
    audioKey: 'mission_vehicle_fly',
    iconName: 'Rocket',
    color: 'bg-purple-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-hauler',
    title: 'Heavy Hauler',
    voicePrompt: 'Heavy hauler! Build a truck with a long trailer. It needs to carry a car.',
    audioScript: 'Heavy hauler! Build a truck, with a long trailer. It needs to carry a car!',
    audioKey: 'mission_vehicle_hauler',
    iconName: 'Container',
    color: 'bg-slate-600',
    world: WorldType.VEHICLE,
  },
  {
    id: 'vehicle-bike',
    title: 'Super Bike',
    voicePrompt: 'Super bike! Build a fast motorcycle. Give it two exhaust pipes!',
    audioScript: 'Super bike! Build a fast motorcycle. Give it two exhaust pipes! Vroom!',
    audioKey: 'mission_vehicle_bike',
    iconName: 'Bike',
    color: 'bg-teal-500',
    world: WorldType.VEHICLE,
  },

  // --- DINO MISSIONS (Level 1) ---
  {
    id: 'dino-rex',
    title: 'T-Rex Titan',
    voicePrompt: 'T-Rex time! Big legs. Tiny arms. And a big tail for balance!',
    audioScript: 'T-Rex time! Big legs... Tiny arms. And a big tail, for balance!',
    audioKey: 'mission_dino_rex',
    iconName: 'Skull',
    color: 'bg-stone-600',
    world: WorldType.DINO,
  },
  {
    id: 'dino-transport',
    title: 'Raptor Unit',
    voicePrompt: 'Raptor truck! Build a cage on wheels. Keep that raptor inside!',
    audioScript: 'Raptor truck! Build a cage on wheels. Keep that raptor inside!',
    audioKey: 'mission_dino_transport',
    iconName: 'Lock',
    color: 'bg-orange-600',
    world: WorldType.DINO,
  },
  {
    id: 'dino-mech',
    title: 'Dino Mech',
    voicePrompt: 'Dino Robot! Build a suit with claws. It looks like a dinosaur!',
    audioScript: 'Dino Robot! Build a suit with claws. It looks just like a dinosaur!',
    audioKey: 'mission_dino_mech',
    iconName: 'Bot',
    color: 'bg-slate-700',
    world: WorldType.DINO,
  },
  {
    id: 'dino-drone',
    title: 'Pteranodon Drone',
    voicePrompt: 'Dino Drone! Give it wings. Fly over the jungle!',
    audioScript: 'Dino Drone! Give it wings. Fly over the jungle! Whoosh!',
    audioKey: 'mission_dino_drone',
    iconName: 'Plane',
    color: 'bg-sky-600',
    world: WorldType.DINO,
  },
  {
    id: 'dino-tank',
    title: 'Tri-Horn Tank',
    voicePrompt: 'Triceratops Tank! Three horns on the front. Built like a tank.',
    audioScript: 'Triceratops Tank! Three horns on the front. Built like a tank.',
    audioKey: 'mission_dino_tank',
    iconName: 'Shield',
    color: 'bg-emerald-700',
    world: WorldType.DINO,
  },
  {
    id: 'dino-dig',
    title: 'Fossil Dig',
    voicePrompt: 'Fossil dig! Build a crane. Lift those heavy bones.',
    audioScript: 'Fossil dig! Build a crane. Lift those heavy bones.',
    audioKey: 'mission_dino_dig',
    iconName: 'Shovel',
    color: 'bg-yellow-700',
    world: WorldType.DINO,
  },
  {
    id: 'dino-lab',
    title: 'Volcano Lab',
    voicePrompt: 'Volcano Lab! Build a science truck. Careful, it is hot!',
    audioScript: 'Volcano Lab! Build a science truck. Careful... it is hot!',
    audioKey: 'mission_dino_lab',
    iconName: 'Flame',
    color: 'bg-red-700',
    world: WorldType.DINO,
  },
  {
    id: 'dino-stego',
    title: 'Solar Stego',
    voicePrompt: 'Solar Stego! Use solar panels for the plates on its back.',
    audioScript: 'Solar Stego! Use solar panels for the plates on its back.',
    audioKey: 'mission_dino_stego',
    iconName: 'Zap',
    color: 'bg-lime-600',
    world: WorldType.DINO,
  },

  // --- CASTLE MISSIONS (Level 1) ---
  {
    id: 'castle-fortress',
    title: 'Mighty Fortress',
    voicePrompt: 'Build a fortress! Thick walls. Strong gate. Keep the bad guys out!',
    audioScript: 'Build a fortress! Thick walls. Strong gate. Keep the bad guys out!',
    audioKey: 'mission_castle_fortress',
    iconName: 'Castle',
    color: 'bg-stone-500',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-dragon',
    title: 'Fire Dragon',
    voicePrompt: 'Fire Dragon! Giant wings. Big mouth. Roar!',
    audioScript: 'Fire Dragon! Giant wings. Big mouth. Roar!',
    audioKey: 'mission_castle_dragon',
    iconName: 'Flame',
    color: 'bg-red-600',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-sword',
    title: 'Hero Sword',
    voicePrompt: 'Hero Sword! Build a shiny sword for the brave knight.',
    audioScript: 'Hero Sword! Build a shiny sword, for the brave knight.',
    audioKey: 'mission_castle_sword',
    iconName: 'Sword',
    color: 'bg-blue-700',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-shield',
    title: 'Giant Shield',
    voicePrompt: 'Giant Shield! Make it huge. Put a design on the front.',
    audioScript: 'Giant Shield! Make it huge. Put a design on the front.',
    audioKey: 'mission_castle_shield',
    iconName: 'Shield',
    color: 'bg-amber-500',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-catapult',
    title: 'Rock Thrower',
    voicePrompt: 'Rock Thrower! Build a catapult on wheels. Launch those rocks!',
    audioScript: 'Rock Thrower! Build a catapult on wheels. Launch those rocks!',
    audioKey: 'mission_castle_catapult',
    iconName: 'Target',
    color: 'bg-orange-800',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-wizard',
    title: 'Wizard Tower',
    voicePrompt: 'Wizard Tower! Make it tall and crooked. Magic happens here.',
    audioScript: 'Wizard Tower! Make it tall, and crooked. Magic happens here!',
    audioKey: 'mission_castle_wizard',
    iconName: 'Sparkles',
    color: 'bg-purple-800',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-trap',
    title: 'Treasure Trap',
    voicePrompt: 'Treasure Trap! Protect the gold. Build a secret trap.',
    audioScript: 'Treasure Trap! Protect the gold... Build a secret trap!',
    audioKey: 'mission_castle_trap',
    iconName: 'Gem',
    color: 'bg-yellow-500',
    world: WorldType.CASTLE,
  },
  {
    id: 'castle-chariot',
    title: 'Battle Chariot',
    voicePrompt: 'Battle Chariot! Two wheels. Fast horses. The King is ready!',
    audioScript: 'Battle Chariot! Two wheels. Fast horses. The King is ready!',
    audioKey: 'mission_castle_chariot',
    iconName: 'Crown',
    color: 'bg-indigo-500',
    world: WorldType.CASTLE,
  },

  // --- LAVA MISSIONS (Level 1) ---
  {
    id: 'lava-surf',
    title: 'Magma Surfer',
    voicePrompt: 'Magma Surfer! Build a surfboard. Ride the hot lava waves!',
    audioScript: 'Magma Surfer! Build a surfboard. Ride the hot lava waves!',
    audioKey: 'mission_lava_surf',
    iconName: 'Waves',
    color: 'bg-orange-500',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-jump',
    title: 'Spring Legs',
    voicePrompt: 'The floor is lava! Build a suit with springy legs. Jump over it!',
    audioScript: 'The floor is lava! Build a suit with springy legs. Jump over it!',
    audioKey: 'mission_lava_jump',
    iconName: 'ArrowUpCircle',
    color: 'bg-red-500',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-escape',
    title: 'Volcano Glider',
    voicePrompt: 'Volcano Glider! The ground is shaking. Build a glider and fly away!',
    audioScript: 'Volcano Glider! The ground is shaking... Build a glider and fly away!',
    audioKey: 'mission_lava_escape',
    iconName: 'Wind',
    color: 'bg-slate-700',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-cool',
    title: 'Ice Cannon',
    voicePrompt: 'Too hot! Build a giant ice cannon. Cool it down.',
    audioScript: 'Too hot! Build a giant ice cannon... Cool it down.',
    audioKey: 'mission_lava_cool',
    iconName: 'Snowflake',
    color: 'bg-cyan-500',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-monster',
    title: 'Lava Eater',
    voicePrompt: 'Lava Monster! Build a silly beast. It eats lava for breakfast!',
    audioScript: 'Lava Monster! Build a silly beast. It eats lava for breakfast! Yummy.',
    audioKey: 'mission_lava_monster',
    iconName: 'Utensils',
    color: 'bg-green-600',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-base',
    title: 'Obsidian Fort',
    voicePrompt: 'Secret Base! Build it inside a black rock. Hide from the dragons.',
    audioScript: 'Secret Base! Build it inside a black rock. Hide from the dragons.',
    audioKey: 'mission_lava_base',
    iconName: 'Shield',
    color: 'bg-stone-800',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-rescue',
    title: 'Rock Rescue',
    voicePrompt: 'Rock Rescue! A friend is stuck. Build a hook to pull them out.',
    audioScript: 'Rock Rescue! A friend is stuck. Build a hook to pull them out.',
    audioKey: 'mission_lava_rescue',
    iconName: 'LifeBuoy',
    color: 'bg-yellow-600',
    world: WorldType.LAVA,
  },
  {
    id: 'lava-drill',
    title: 'Magma Drill',
    voicePrompt: 'Magma Drill! Point it down. Drill deep into the earth.',
    audioScript: 'Magma Drill! Point it down. Drill deep, into the earth.',
    audioKey: 'mission_lava_drill',
    iconName: 'ArrowDown',
    color: 'bg-red-800',
    world: WorldType.LAVA,
  },

  // --- SPACE MISSIONS (Level 1) ---
  {
    id: 'space-rocket',
    title: 'Moon Rocket',
    voicePrompt: 'Moon Rocket! Build it super tall. 3... 2... 1... Blast off!',
    audioScript: 'Moon Rocket! Build it super tall. Three... Two... One... Blast off!',
    audioKey: 'mission_space_rocket',
    iconName: 'Rocket',
    color: 'bg-sky-600',
    world: WorldType.SPACE,
  },
  {
    id: 'space-alien',
    title: 'Alien Friend',
    voicePrompt: 'Alien Friend! Green skin. Lots of eyes. Make it friendly!',
    audioScript: 'Alien Friend! Green skin. Lots of eyes. Make it friendly!',
    audioKey: 'mission_space_alien',
    iconName: 'Ghost',
    color: 'bg-lime-500',
    world: WorldType.SPACE,
  },
  {
    id: 'space-rover',
    title: 'Mars Rover',
    voicePrompt: 'Mars Rover! Six wheels. Drive over the bumpy red rocks.',
    audioScript: 'Mars Rover! Six wheels. Drive over the bumpy red rocks.',
    audioKey: 'mission_space_rover',
    iconName: 'Truck',
    color: 'bg-orange-600',
    world: WorldType.SPACE,
  },
  {
    id: 'space-station',
    title: 'Space Station',
    voicePrompt: 'Space Station! A floating house in the stars. Astronauts live here.',
    audioScript: 'Space Station! A floating house in the stars. Astronauts live here.',
    audioKey: 'mission_space_station',
    iconName: 'Satellite',
    color: 'bg-slate-500',
    world: WorldType.SPACE,
  },
  {
    id: 'space-laser',
    title: 'Meteor Smasher',
    voicePrompt: 'Meteor Smasher! Build a spaceship with lasers. Zap the rocks!',
    audioScript: 'Meteor Smasher! Build a spaceship with lasers. Zap the rocks! Pew pew!',
    audioKey: 'mission_space_laser',
    iconName: 'Zap',
    color: 'bg-yellow-400',
    world: WorldType.SPACE,
  },
  {
    id: 'space-ufo',
    title: 'Spinning UFO',
    voicePrompt: 'Spinning UFO! A round flying saucer. Spin it around!',
    audioScript: 'Spinning UFO! A round flying saucer. Spin it around!',
    audioKey: 'mission_space_ufo',
    iconName: 'Disc',
    color: 'bg-teal-500',
    world: WorldType.SPACE,
  },
  {
    id: 'space-jetpack',
    title: 'Super Jetpack',
    voicePrompt: 'Super Jetpack! Fire on the bottom. Fly like a rocket!',
    audioScript: 'Super Jetpack! Fire on the bottom. Fly like a rocket! Whoosh!',
    audioKey: 'mission_space_jetpack',
    iconName: 'Wind',
    color: 'bg-red-500',
    world: WorldType.SPACE,
  },
  {
    id: 'space-robot',
    title: 'Robo-Helper',
    voicePrompt: 'Robo-Helper! Clamp hands. Helpful beep boops. Fix the ship!',
    audioScript: 'Robo-Helper! Clamp hands. Helpful beep boops. Fix the ship!',
    audioKey: 'mission_space_robot',
    iconName: 'Bot',
    color: 'bg-indigo-500',
    world: WorldType.SPACE,
  }
];

export const LEVEL_2_MISSIONS: Mission[] = [
  // --- TINY BUILDERS (Level 2) ---
  // Simple concepts, colors, and basic stacking
  // Instructions are simple full sentences for better TTS flow.
  
  // VEHICLE (5 Missions)
  {
    id: 'tiny-car',
    title: 'Blue Car',
    voicePrompt: "Let's build a blue car. Vroom vroom!",
    audioScript: "Let's build a blue car. The wheels on the car go round and round. Round and round.",
    audioKey: 'tiny_car',
    iconName: 'Car',
    color: 'bg-blue-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'tiny-bus',
    title: 'Yellow Bus',
    voicePrompt: "Let's make a yellow bus. Beep beep!",
    audioScript: "Let's make a yellow bus. The wheels on the bus go round and round. All through the town.",
    audioKey: 'tiny_bus',
    iconName: 'Truck',
    color: 'bg-yellow-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'tiny-train',
    title: 'Choo Choo',
    voicePrompt: "Build a long train. Choo choo!",
    audioScript: "Build a long train. Choo choo! Down by the station, see the little trains. All in a row.",
    audioKey: 'tiny_train',
    iconName: 'Train',
    color: 'bg-red-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'tiny-boat',
    title: 'Blue Boat',
    voicePrompt: "Build a blue boat. It floats!",
    audioScript: "Build a blue boat. Row, row, row your boat. Gently down the stream. Merrily, merrily, merrily, merrily.",
    audioKey: 'tiny_boat',
    iconName: 'Ship',
    color: 'bg-sky-500',
    world: WorldType.VEHICLE,
  },
  {
    id: 'tiny-plane',
    title: 'Big Plane',
    voicePrompt: "Make a big plane. Fly high!",
    audioScript: "Make a big plane. Zoom, zoom, zoom! We're going to the moon! Zoom, zoom, zoom! We're leaving very soon!",
    audioKey: 'tiny_plane',
    iconName: 'Plane',
    color: 'bg-blue-600',
    world: WorldType.VEHICLE,
  },

  // DINO (Nature) (3 Missions)
  {
    id: 'tiny-dino',
    title: 'Green Dino',
    voicePrompt: "Build a green dino. Roar!",
    audioScript: "Build a green dino. Dino, dino, turn around! Dino, dino, touch the ground!",
    audioKey: 'tiny_dino',
    iconName: 'Trees',
    color: 'bg-green-600',
    world: WorldType.DINO,
  },
  {
    id: 'tiny-egg',
    title: 'Big Egg',
    voicePrompt: "Make a big egg. It is round.",
    audioScript: "Make a big egg. Humpty Dumpty sat on a wall. Humpty Dumpty had a great big fall.",
    audioKey: 'tiny_egg',
    iconName: 'Circle',
    color: 'bg-white',
    world: WorldType.DINO,
  },
  {
    id: 'tiny-tree',
    title: 'Tall Tree',
    voicePrompt: "Build a tall tree. So green!",
    audioScript: "Build a tall tree. Rock-a-bye baby, on the tree top. When the wind blows, the cradle will rock.",
    audioKey: 'tiny_tree',
    iconName: 'Trees',
    color: 'bg-green-500',
    world: WorldType.DINO,
  },

  // CASTLE (Building) (4 Missions)
  {
    id: 'tiny-tower',
    title: 'Tall Tower',
    voicePrompt: "Build a tall tower. Up up up!",
    audioScript: "Build a tall tower. London Bridge is falling down, falling down, falling down. My fair lady.",
    audioKey: 'tiny_tower',
    iconName: 'Castle',
    color: 'bg-indigo-400',
    world: WorldType.CASTLE,
  },
  {
    id: 'tiny-wall',
    title: 'Big Wall',
    voicePrompt: "Make a big wall. Stack them high.",
    audioScript: "Make a big wall. Ten green bottles standing on the wall. Ten green bottles standing on the wall.",
    audioKey: 'tiny_wall',
    iconName: 'LayoutTemplate',
    color: 'bg-stone-500',
    world: WorldType.CASTLE,
  },
  {
    id: 'tiny-blocks',
    title: '3 Blocks',
    voicePrompt: "Stack three blocks. One, two, three!",
    audioScript: "Stack three blocks. One, two, buckle my shoe. Three, four, knock on the door.",
    audioKey: 'tiny_blocks',
    iconName: 'Layers',
    color: 'bg-purple-400',
    world: WorldType.CASTLE,
  },
  {
    id: 'tiny-house',
    title: 'Red House',
    voicePrompt: "Build a red house. A safe home.",
    audioScript: "Build a red house. Little cabin in the wood. Little man by the window stood.",
    audioKey: 'tiny_house',
    iconName: 'Home',
    color: 'bg-red-500',
    world: WorldType.CASTLE,
  },

  // LAVA (Colors/Shapes) (3 Missions)
  {
    id: 'tiny-fire',
    title: 'Hot Fire',
    voicePrompt: "Make a hot fire. Very red!",
    audioScript: "Make a hot fire. Hot cross buns! Hot cross buns! One a penny, two a penny. Hot cross buns!",
    audioKey: 'tiny_fire',
    iconName: 'Flame',
    color: 'bg-red-600',
    world: WorldType.LAVA,
  },
  {
    id: 'tiny-flower',
    title: 'Red Flower',
    voicePrompt: "Build a red flower. So pretty!",
    audioScript: "Build a red flower. Mary, Mary, quite contrary. How does your garden grow?",
    audioKey: 'tiny_flower',
    iconName: 'Flower',
    color: 'bg-red-400',
    world: WorldType.LAVA,
  },
  {
    id: 'tiny-red-tower',
    title: 'Red Tower',
    voicePrompt: "Make a red tower. Super high!",
    audioScript: "Make a red tower. Hickory dickory dock. The mouse ran up the clock.",
    audioKey: 'tiny_red_tower',
    iconName: 'ArrowUpCircle',
    color: 'bg-red-700',
    world: WorldType.LAVA,
  },

  // SPACE (Shapes) (3 Missions)
  {
    id: 'tiny-star',
    title: 'Shiny Star',
    voicePrompt: "Build a shiny star. Twinkle twinkle!",
    audioScript: "Build a shiny star. Twinkle, twinkle, little star. How I wonder what you are.",
    audioKey: 'tiny_star',
    iconName: 'Star',
    color: 'bg-yellow-400',
    world: WorldType.SPACE,
  },
  {
    id: 'tiny-moon',
    title: 'White Moon',
    voicePrompt: "Make a white moon. Goodnight!",
    audioScript: "Make a white moon. Hey diddle diddle, The cat and the fiddle, The cow jumped over the moon.",
    audioKey: 'tiny_moon',
    iconName: 'Moon',
    color: 'bg-slate-300',
    world: WorldType.SPACE,
  },
  {
    id: 'tiny-smile',
    title: 'Happy Face',
    voicePrompt: "Build a happy face. Big smile!",
    audioScript: "Build a happy face. If you're happy and you know it, clap your hands! If you're happy and you know it, clap your hands!",
    audioKey: 'tiny_smile',
    iconName: 'Smile',
    color: 'bg-yellow-300',
    world: WorldType.SPACE,
  }
];